language: cpp

compiler: 
  - gcc
  - clang

install: sudo -E ./scripts/install.sh
before_script: ./scripts/prebuild.sh
script: make

# coverity stuff:
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HJsgD1B2gys+45zkGqFD8riF+fKMKGiq4956nXePXJATXCQEJKOGfz+rmw8nVaBOxKvVjyk8l5WIiXVoOQ6ZlFkhCz1sttBZn6x123vIR1ruP6Ze8B2OJnRzPt3ZTJJvlPyonhOMI+lXYnVCRwa+uwAiIkAyl4bDsCtSjlXeIV8="

addons:
  coverity_scan:
    project:
      name: "madeso/ride"
      description: "Ride is a Rust IDE"
    notification_email: sir.gustav.the.coder@gmail.com
    build_command_prepend: "sudo -E ./scripts/install.sh; ./scripts/prebuild.sh"
    build_command:   "make"
    branch_pattern: master

# don't run clang with coverity
matrix:
  exclude:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH=1
