language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - gcc-multilib
      - g++-multilib
      - libgtk2.0-dev
      - libwebkit-dev
      - libc6-i386

os:
  - linux

# osx_image: 7.2

matrix:
  include:
    - os: osx
      compiler: clang
  exclude:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH=1
  allow_failures:
    - os: osx


# gcc update grabbed from https://github.com/ldc-developers/ldc/blob/master/.travis.yml
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-4.9"; export CXX="g++-4.9"; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$PATH:$TRAVIS_BUILD_DIR/osx-deps/cmake/CMake.app/Contents/bin; fi;
  - ./scripts/travis-dependencies.sh
before_script: cmake .
script: make

# coverity stuff:
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HJsgD1B2gys+45zkGqFD8riF+fKMKGiq4956nXePXJATXCQEJKOGfz+rmw8nVaBOxKvVjyk8l5WIiXVoOQ6ZlFkhCz1sttBZn6x123vIR1ruP6Ze8B2OJnRzPt3ZTJJvlPyonhOMI+lXYnVCRwa+uwAiIkAyl4bDsCtSjlXeIV8="

addons:
  coverity_scan:
    project:
      name: "madeso/ride"
    notification_email: sir.gustav.the.coder@gmail.com
    build_command_prepend: "$CC --version; ./scripts/travis-install.sh; ./scripts/travis-prebuild.sh"
    build_command:   "make"
    branch_pattern: coverity_scan
