language: cpp

compiler: 
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --assume-yes graphviz doxygen libwxgtk2.8-dev libprotobuf-dev protobuf-compiler

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_USE_CLANG_FORMAT=OFF -DBUILD_USE_CPPLINT=OFF -DBUILD_USE_DOXYGEN=OFF -DBUILD_USE_DOXYGEN_GLOBAL=OFF -DBUILD_USE_CPPCHECK=OFF ..

script: make
