language: cpp

compiler: 
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --assume-yes graphviz doxygen libwxgtk2.8-dev libprotobuf-dev protobuf-compiler

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
