language: cpp

sudo: false

compiler:
  - gcc
  - clang


# cmake 3 https://github.com/travis-ci/travis-ci/issues/4631

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - gcc-multilib
      - g++-multilib
      - libgtk2.0-dev
      - libwebkit-dev
      - libc6-i386
      - cmake
      - cmake-data

os:
  - linux

# osx_image: 7.2

matrix:
  include:
    - os: osx
      compiler: clang
  exclude:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH=1
  allow_failures:
    - os: osx


# gcc update grabbed from https://github.com/ldc-developers/ldc/blob/master/.travis.yml
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-4.9"; export CXX="g++-4.9"; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$PATH:$TRAVIS_BUILD_DIR/osx-deps/cmake/CMake.app/Contents/bin; fi;
  - ./scripts/travis-dependencies.sh
before_script: cmake .
script: make