language: cpp

compiler: 
  - gcc
  - clang

install: sudo -E ./scripts/install.sh
script: ./scripts/build.sh

# coverity stuff:
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HJsgD1B2gys+45zkGqFD8riF+fKMKGiq4956nXePXJATXCQEJKOGfz+rmw8nVaBOxKvVjyk8l5WIiXVoOQ6ZlFkhCz1sttBZn6x123vIR1ruP6Ze8B2OJnRzPt3ZTJJvlPyonhOMI+lXYnVCRwa+uwAiIkAyl4bDsCtSjlXeIV8="

addons:
  coverity_scan:
    project:
      name: "madeso/ride"
      description: "Ride is a Rust IDE"
    notification_email: sir.gustav.the.coder@gmail.com
    build_command_prepend: "sudo -E ./scripts/install.sh"
    build_command:   "./scripts/build.sh"
#todo, change this asap
    branch_pattern: master
