branches:
  only:
    - master

image: Visual Studio 2015

install:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor-install.py'

before_build:
  - cmd: 'scripts\appveyor-cmake.bat'

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true
  project: build/ride.sln