branches:
  only:
    - master

image: Visual Studio 2015

install:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py install'

before_build:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py cmake'

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py build'

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true
